name: ridgesfm
channels:
  - pytorch3d
  - iopath
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=2.0.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.2.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - cryptography=3.3.1
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - faiss-cpu=1.6.5
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fvcore=0.1.2.post20210115
  - gettext=0.19.8.1
  - glib=2.66.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.3
  - harfbuzz=2.7.4
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - intel-openmp=2020.2
  - iopath=0.1.3.post20210120
  - ipykernel=5.4.2
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.0
  - jupyter_server=1.2.2
  - jupyterlab=3.0.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.1.2
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libfaiss=1.6.5
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.0.1
  - libnghttp2=1.41.0
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclassic=0.2.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nettle=3.6
  - ninja=1.10.2
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.60
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=4.5.0
  - openh264=2.1.1
  - openssl=1.1.1i
  - packaging=20.8
  - pandoc=2.11.3.2
  - pandocfilters=1.4.3
  - parso=0.7.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - pixman=0.40.0
  - portalocker=2.0.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.11
  - ptyprocess=0.7.0
  - py-opencv=4.5.0
  - pycparser=2.20
  - pygments=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.6.0
  - pytorch3d=0.3.0
  - pytz=2020.5
  - pyyaml=5.4
  - pyzmq=21.0.1
  - qt=5.12.9
  - readline=8.0
  - requests=2.25.1
  - send2trash=1.5.0
  - setuptools=51.3.3
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.34.0
  - tabulate=0.8.7
  - termcolor=1.1.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - torchvision=0.7.0
  - tornado=6.1
  - tqdm=4.55.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - antlr4-python3-runtime==4.8
    - hydra-core==1.0.5
    - importlib-resources==5.1.0
    - omegaconf==2.0.6
    - pykeops==1.4.2

